name: Frontend CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: List Project Files
        run: ls -la

      - name: Verify HTML
        run: cat index.html

      - name: Build Successful
        run: echo "Frontend Build Successful!"
